name = "SagbiGbDetection"
uuid = "1b6c37c6-8632-4342-94fc-bd2a198ddbb5"
authors = ["Viktoriia Borovik, Timothy Duff, and Elima Shehu"]
version = "0.1.0"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Singular = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"

[compat]
Oscar = "0.12.1"
Singular = "0.18.13"
julia="1.8"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown","Test"]
